### ISSUE TITLE
Decide where repo should be

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/21cmSense#22]
We should decide on where the official repo should be -- could stay at jpober/21cmSense, we could try moving it to RASG, or we could call it 21cmSense2.

I hope @jpober has an opinion :-)

**Comment by jpober** [comment]
I was actually just talking about this with Matt K.  My two thoughts are (1) I don't want anyone trying to use the old 21cmSense code any more and (2) you, Steven, should get maximal credit as the driver behind this.  I think point (1) argues against anything like 21cmSense2.  I'd be fine with having the new code hosted from my repository, but that doesn't accomplished (2).  So I think having it either on your repository or as a RASG-affiliate code would be best.  When can then have jpober/21cmSense redirect there.

**Comment by steven-murray** [comment]
I think that having it on RASG-affiliates is probably best, as it allows for more visibility from more people. Do you know when the next RASG meeting is (or was that this morning...?).

**Comment by jpober** [comment]
I don't think there are really RASG meetings, but we could convene one.
RASG managers have a closed Slack channel that gets used occasionally, I
can let them know we're considering this and see how they feel.

**Comment by steven-murray** [comment]
Thanks!

**Comment by jpober** [comment]
The RASG affiliates guidelines are here:
https://github.com/RadioAstronomySoftwareGroup/RadioAstronomySoftwareGroup.github.io#affiliate-organization.
Unfortunately the GPL license is a no-no.  Are you strongly attached to it?

**Comment by steven-murray** [comment]
Not even slightly -- I didn't realize/had forgotten that it was GPL
licensed. I'll see what I can do about that.

**Comment by steven-murray** [comment]
It's going to RASG-affiliates
