### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/21cmSense#24]
Instead of travis

**Comment by mkolopanis** [comment]
Are you also interested in having the actions just execute the `tox` test suite instead of different runs for each OS/python-version combination?

**Comment by steven-murray** [comment]
I have done that with travis before, but not actions. Would certainly be interested if it's easy enough and doesn't require hacks

**Comment by mkolopanis** [comment]
I can probably try it out. We'll see if I get there before you.
