### ISSUE TITLE
Decide on a release/versioning strategy

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/21cmSense#25]
I vote for semi-automatic releases using github actions, and strict semantic versioning. Calling in @jpober for opinions.

**Comment by jpober** [comment]
No strong opinions here.  I'd like to do some development on the code
myself one day, so this might be a high bar for my antiquated coding
practices to clear, but maybe that's for the best.

**Comment by steven-murray** [comment]
I think this works fine right now. We use `setuptools_scm` to do versioning. Every time we merge to main, we use `github-tag-actions` to check the commit messages for kinds of commits. It auto-tags a new version, and that sets off the deploy script which deploys the new version to pypi. 

The only downside here is that the changelog is not updated with the new version. Something like [this](https://py-pkgs.org/07-releasing-versioning) might work to do that automatically. @mkolopanis any thoughts?
