### ISSUE TITLE
Self consistency in tests

### ISSUE THREAD

**Issue by mkolopanis** [steven-murray/21cmSense#29]
The default value of parameter `ndecimals` in `get_redundant_baselines` is 1. However, when called via `grid_baselines` this parameter is defaulted to 0. Should one of these calls be given an `ndecimals` argument to make the calculations identical or is the difference in `ndecimals` deliberate? 
https://github.com/steven-murray/21cmSense/blob/0e83ebd5d6359b9d1571ff06056abca5c6908b0e/tests/test_observatory.py#L75-L86

**Comment by steven-murray** [comment]
I think probably `grid_baselines` should be modified to use `ndecimals=1`.

**Comment by mkolopanis** [comment]
I can add this to my current PR if you don't mind it being tacked in there.

**Comment by steven-murray** [comment]
I cannot abide the idea.

jks.
